-- ============================================================
-- Mai Little Mermaid — Supabase Setup
-- Run this once in Supabase: SQL Editor → New Query → Run
-- ============================================================

-- 1. CREATE PRODUCTS TABLE
create table public.products (
  id          bigint generated by default as identity primary key,
  name        text    not null,
  type        text    not null,
  price       integer not null,
  metal       text    not null,
  colour      text,
  grad        text    not null default 'g1',
  image_url   text,
  available   boolean not null default true,
  is_new      boolean not null default false,
  created_at  timestamptz not null default now()
);

-- 2. ROW LEVEL SECURITY
alter table public.products enable row level security;

-- Anyone can read products (public shop)
create policy "Public read"
  on public.products for select
  using (true);

-- Only signed-in users (Maile) can add / edit / delete
create policy "Auth insert"
  on public.products for insert
  with check (auth.role() = 'authenticated');

create policy "Auth update"
  on public.products for update
  using (auth.role() = 'authenticated');

create policy "Auth delete"
  on public.products for delete
  using (auth.role() = 'authenticated');

-- 3. SEED INITIAL PRODUCTS
insert into public.products (name, type, price, metal, colour, grad, available, is_new) values
  ('Seafoam Glass Bracelet', 'Bracelet', 55,  'Sterling Silver', 'Seafoam',     'g1', true,  true),
  ('Cobalt Drop Earrings',   'Earrings', 72,  'Gold Fill',       'Cobalt Blue', 'g2', true,  true),
  ('Amber Charm Necklace',   'Necklace', 130, 'Gold Fill',       'Amber',       'g3', true,  false),
  ('Multi Stone Necklace',   'Necklace', 92,  'Sterling Silver', 'Mixed',       'g4', false, false),
  ('Forest Green Studs',     'Earrings', 47,  'Sterling Silver', 'Green',       'g5', true,  false),
  ('Lavender Sea Pendant',   'Necklace', 130, 'Gold Fill',       'Lavender',    'g6', true,  true),
  ('Clear Glass Bracelet',   'Bracelet', 55,  'Sterling Silver', 'Clear',       'g7', false, false),
  ('Coral Stone Earrings',   'Earrings', 72,  'Gold Fill',       'Coral Pink',  'g8', true,  false);

-- ============================================================
-- 4. SITE CONTENT TABLE (for admin Content editor)
-- ============================================================

create table public.site_content (
  key        text primary key,
  value      text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

-- Anyone can read (needed for index.html to load content)
create policy "Public read content"
  on public.site_content for select
  using (true);

-- Only signed-in admin can edit
create policy "Auth upsert content"
  on public.site_content for insert
  with check (auth.role() = 'authenticated');

create policy "Auth update content"
  on public.site_content for update
  using (auth.role() = 'authenticated');

-- 5. PHOTO STORAGE BUCKET + POLICIES
-- Run this in SQL Editor — it creates the bucket AND the upload permission

insert into storage.buckets (id, name, public)
  values ('product-images', 'product-images', true)
  on conflict (id) do update set public = true;

-- Let authenticated admin upload files
create policy "Authenticated can upload product-images"
  on storage.objects for insert
  with check (
    bucket_id = 'product-images'
    and auth.role() = 'authenticated'
  );

-- Let the public read / view all images
create policy "Public can read product-images"
  on storage.objects for select
  using (bucket_id = 'product-images');

-- Let authenticated admin delete files
create policy "Authenticated can delete product-images"
  on storage.objects for delete
  using (
    bucket_id = 'product-images'
    and auth.role() = 'authenticated'
  );

-- ============================================================
-- AFTER RUNNING THIS:
-- 1. Go to Authentication → Users → Add User
--    Create Maile's login email + password
-- 2. Copy your Project URL and anon key from
--    Project Settings → API
-- 3. Paste both into admin.html and shop.html
--    where it says YOUR_SUPABASE_URL / YOUR_SUPABASE_ANON_KEY
-- ============================================================
