-- ============================================================
-- Mai Little Mermaid — Complete Supabase Setup
-- Fresh install — run this once in a new project:
--   SQL Editor → New Query → paste all → Run
-- ============================================================


-- ============================================================
-- 1. PRODUCTS
-- ============================================================

create table public.products (
  id             bigint generated by default as identity primary key,
  name           text        not null,
  type           text        not null,
  price          integer     not null,
  metal          text        not null,
  colour         text,
  grad           text        not null default 'g1',
  image_url      text,
  extra_images   text        not null default '[]',
  available      boolean     not null default true,
  is_new         boolean     not null default false,
  reserved_until timestamptz,
  created_at     timestamptz not null default now()
);

alter table public.products enable row level security;

-- Public shop can read all products
create policy "products: public read"
  on public.products for select
  using (true);

-- Only Maile (authenticated) can create / update / delete via admin.html
create policy "products: auth insert"
  on public.products for insert
  with check (auth.role() = 'authenticated');

create policy "products: auth update"
  on public.products for update
  using (auth.role() = 'authenticated');

create policy "products: auth delete"
  on public.products for delete
  using (auth.role() = 'authenticated');


-- ============================================================
-- 2. RESERVE_PRODUCT — atomic 10-minute cart hold
--    Called by api/reserve-product.js (service role key).
--    Returns the new reserved_until timestamp, or NULL if the
--    product is unavailable or already held by someone else.
-- ============================================================

create or replace function public.reserve_product(p_id bigint)
returns timestamptz
language plpgsql
security definer
as $$
declare
  v_until    timestamptz := now() + interval '10 minutes';
  v_updated  int;
begin
  update public.products
  set    reserved_until = v_until
  where  id             = p_id
    and  available      = true
    and  (reserved_until is null or reserved_until < now());

  get diagnostics v_updated = row_count;

  if v_updated = 0 then
    return null;   -- already reserved or sold
  end if;

  return v_until;
end;
$$;

grant execute on function public.reserve_product(bigint)
  to anon, authenticated, service_role;


-- ============================================================
-- 3. ORDERS — fulfillment tracking
--    Rows are inserted by api/mark-sold.js on successful payment.
--    Status is updated by admin.html via api/update-order-status.js.
-- ============================================================

create table public.orders (
  id                uuid        primary key default gen_random_uuid(),
  stripe_session_id text        unique not null,
  status            text        not null default 'new'
                      check (status in ('new', 'packed', 'shipped')),
  fulfillment_note  text,
  shipped_at        timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- Auto-bump updated_at on every change
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger orders_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

-- No direct public access — all reads/writes go through serverless
-- functions that carry the service_role key
alter table public.orders enable row level security;


-- ============================================================
-- 4. SITE CONTENT — admin editable copy for homepage
-- ============================================================

create table public.site_content (
  key        text        primary key,
  value      text        not null default '',
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

-- Public can read (shop pages pull hero/about text)
create policy "site_content: public read"
  on public.site_content for select
  using (true);

-- Only Maile can write
create policy "site_content: auth insert"
  on public.site_content for insert
  with check (auth.role() = 'authenticated');

create policy "site_content: auth update"
  on public.site_content for update
  using (auth.role() = 'authenticated');


-- ============================================================
-- 5. ENQUIRIES — custom order requests from shop.html
--    Inserted by api/submit-enquiry.js (public, no auth required).
--    Read and updated by admin.html via api/list-enquiries.js
--    and api/update-enquiry-status.js (service_role key, auth-gated).
-- ============================================================

create table public.enquiries (
  id         uuid        primary key default gen_random_uuid(),
  name       text,
  email      text        not null,
  piece_type text,
  metals     text,
  materials  text,
  message    text,
  status     text        not null default 'new'
               check (status in ('new', 'replied', 'declined')),
  created_at timestamptz not null default now()
);

alter table public.enquiries enable row level security;

-- Public (shop visitors) can submit enquiries — no login needed
create policy "enquiries: public insert"
  on public.enquiries for insert
  with check (true);

-- Reads and updates only go through serverless functions carrying
-- the service_role key which bypasses RLS — no extra policies needed.


-- ============================================================
-- 6. STORAGE — product photos bucket
-- ============================================================

insert into storage.buckets (id, name, public)
  values ('product-images', 'product-images', true)
  on conflict (id) do update set public = true;

create policy "product-images: public read"
  on storage.objects for select
  using (bucket_id = 'product-images');

create policy "product-images: auth upload"
  on storage.objects for insert
  with check (
    bucket_id = 'product-images'
    and auth.role() = 'authenticated'
  );

create policy "product-images: auth delete"
  on storage.objects for delete
  using (
    bucket_id = 'product-images'
    and auth.role() = 'authenticated'
  );


-- ============================================================
-- 6. SEED PRODUCTS (delete and re-insert for a clean slate)
-- ============================================================

truncate public.products restart identity cascade;

insert into public.products
  (name, type, price, metal, colour, grad, available, is_new)
values
  ('Seafoam Glass Bracelet', 'Bracelet', 55,  'Sterling Silver', 'Seafoam',     'g1', true,  true),
  ('Cobalt Drop Earrings',   'Earrings', 72,  'Gold Fill',       'Cobalt Blue', 'g2', true,  true),
  ('Amber Charm Necklace',   'Necklace', 130, 'Gold Fill',       'Amber',       'g3', true,  false),
  ('Multi Stone Necklace',   'Necklace', 92,  'Sterling Silver', 'Mixed',       'g4', false, false),
  ('Forest Green Studs',     'Earrings', 47,  'Sterling Silver', 'Green',       'g5', true,  false),
  ('Lavender Sea Pendant',   'Necklace', 130, 'Gold Fill',       'Lavender',    'g6', true,  true),
  ('Clear Glass Bracelet',   'Bracelet', 55,  'Sterling Silver', 'Clear',       'g7', false, false),
  ('Coral Stone Earrings',   'Earrings', 72,  'Gold Fill',       'Coral Pink',  'g8', true,  false);


-- ============================================================
-- DONE. Next steps:
--
-- 1. Authentication → Users → Add user
--    Create Maile's login (email + password)
--
-- 2. Project Settings → API
--    Copy "Project URL" and "anon public" key
--    Paste into: admin.html  (SUPABASE_URL / SUPABASE_ANON_KEY)
--                shop.html   (same two values)
--                shop1.html  (same two values)
--
-- 3. Vercel → Project → Settings → Environment Variables
--    Add:  SUPABASE_URL             (Project URL from step 2)
--          SUPABASE_SERVICE_ROLE_KEY (service_role key — NOT the anon key)
--          STRIPE_SECRET_KEY         (from stripe.com dashboard)
--          RESEND_API_KEY            (from resend.com — free tier)
-- ============================================================
