-- ============================================================
-- Mai Little Mermaid — Supabase Setup
-- Run this once in Supabase: SQL Editor → New Query → Run
-- ============================================================

-- 1. CREATE PRODUCTS TABLE
create table public.products (
  id          bigint generated by default as identity primary key,
  name        text    not null,
  type        text    not null,
  price       integer not null,
  metal       text    not null,
  colour      text,
  grad        text    not null default 'g1',
  image_url   text,
  available   boolean not null default true,
  is_new      boolean not null default false,
  created_at  timestamptz not null default now()
);

-- 2. ROW LEVEL SECURITY
alter table public.products enable row level security;

-- Anyone can read products (public shop)
create policy "Public read"
  on public.products for select
  using (true);

-- Only signed-in users (Maile) can add / edit / delete
create policy "Auth insert"
  on public.products for insert
  with check (auth.role() = 'authenticated');

create policy "Auth update"
  on public.products for update
  using (auth.role() = 'authenticated');

create policy "Auth delete"
  on public.products for delete
  using (auth.role() = 'authenticated');

-- 3. SEED INITIAL PRODUCTS
insert into public.products (name, type, price, metal, colour, grad, available, is_new) values
  ('Seafoam Glass Bracelet', 'Bracelet', 55,  'Sterling Silver', 'Seafoam',     'g1', true,  true),
  ('Cobalt Drop Earrings',   'Earrings', 72,  'Gold Fill',       'Cobalt Blue', 'g2', true,  true),
  ('Amber Charm Necklace',   'Necklace', 130, 'Gold Fill',       'Amber',       'g3', true,  false),
  ('Multi Stone Necklace',   'Necklace', 92,  'Sterling Silver', 'Mixed',       'g4', false, false),
  ('Forest Green Studs',     'Earrings', 47,  'Sterling Silver', 'Green',       'g5', true,  false),
  ('Lavender Sea Pendant',   'Necklace', 130, 'Gold Fill',       'Lavender',    'g6', true,  true),
  ('Clear Glass Bracelet',   'Bracelet', 55,  'Sterling Silver', 'Clear',       'g7', false, false),
  ('Coral Stone Earrings',   'Earrings', 72,  'Gold Fill',       'Coral Pink',  'g8', true,  false);

-- ============================================================
-- MIGRATION: add extra_images column (run if table already exists)
-- ============================================================
alter table public.products
  add column if not exists extra_images text not null default '[]';

-- ============================================================
-- 4. SITE CONTENT TABLE (for admin Content editor)
-- ============================================================

create table public.site_content (
  key        text primary key,
  value      text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

-- Anyone can read (needed for index.html to load content)
create policy "Public read content"
  on public.site_content for select
  using (true);

-- Only signed-in admin can edit
create policy "Auth upsert content"
  on public.site_content for insert
  with check (auth.role() = 'authenticated');

create policy "Auth update content"
  on public.site_content for update
  using (auth.role() = 'authenticated');

-- 5. PHOTO STORAGE BUCKET + POLICIES
-- Run this in SQL Editor — it creates the bucket AND the upload permission

insert into storage.buckets (id, name, public)
  values ('product-images', 'product-images', true)
  on conflict (id) do update set public = true;

-- Let authenticated admin upload files
create policy "Authenticated can upload product-images"
  on storage.objects for insert
  with check (
    bucket_id = 'product-images'
    and auth.role() = 'authenticated'
  );

-- Let the public read / view all images
create policy "Public can read product-images"
  on storage.objects for select
  using (bucket_id = 'product-images');

-- Let authenticated admin delete files
create policy "Authenticated can delete product-images"
  on storage.objects for delete
  using (
    bucket_id = 'product-images'
    and auth.role() = 'authenticated'
  );

-- ============================================================
-- MIGRATIONS (run these after initial setup if upgrading)
-- ============================================================

-- Add extra_images column for multi-photo gallery
alter table public.products
  add column if not exists extra_images text not null default '[]';

-- Add reserved_until for cart hold / 10-minute reservation
alter table public.products
  add column if not exists reserved_until timestamptz;

-- RPC used by api/reserve-product.js to atomically claim a product.
-- Returns the new reserved_until timestamp, or NULL if the product
-- was unavailable / already held by someone else.
create or replace function public.reserve_product(p_id bigint)
returns timestamptz
language plpgsql
security definer
as $$
declare
  v_until timestamptz := now() + interval '10 minutes';
  v_updated int;
begin
  update public.products
  set reserved_until = v_until
  where id = p_id
    and available = true
    and (reserved_until is null or reserved_until < now());

  get diagnostics v_updated = row_count;

  if v_updated = 0 then
    return null;
  end if;

  return v_until;
end;
$$;

-- Grant execute to all roles (the service role key calls this)
grant execute on function public.reserve_product(bigint) to anon, authenticated, service_role;

-- Orders table — stores fulfillment status per Stripe session.
-- Created automatically by mark-sold.js when a payment is confirmed.
-- Updated by admin.html when Maile marks orders packed / shipped.
create table if not exists public.orders (
  id                 uuid primary key default gen_random_uuid(),
  stripe_session_id  text unique not null,
  status             text not null default 'new'
                       check (status in ('new', 'packed', 'shipped')),
  fulfillment_note   text,
  shipped_at         timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- Auto-update updated_at on any change
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger orders_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

-- Service role key has full access; anon/authenticated have no direct access
-- (all writes go through serverless functions that use the service role key)
alter table public.orders enable row level security;

-- ============================================================
-- AFTER RUNNING THIS:
-- 1. Go to Authentication → Users → Add User
--    Create Maile's login email + password
-- 2. Copy your Project URL and anon key from
--    Project Settings → API
-- 3. Paste both into admin.html and shop.html
--    where it says YOUR_SUPABASE_URL / YOUR_SUPABASE_ANON_KEY
-- 4. Add RESEND_API_KEY to Vercel environment variables
--    (get a free key at resend.com)
-- ============================================================
